name: cryptofinance
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - pandas
  - numpy
  - matplotlib
  - arrow
  - pyarrow
  - dask
  - python-dotenv
  - scikit-learn
  - shap
  - mlflow
  - yfinance
  - ipykernel